[phases.setup]
# Node.js と pnpm を有効化
pkgs = ["nodejs", "corepack"]

[phases.install]
cmd = "corepack enable && pnpm install --frozen-lockfile"

[phases.build]
cmd = "pnpm run build"

[start]
cmd = "pnpm start" 